version: 1.0.{build}
shallow_clone: true
clone_depth: 1

build:
    - ps: msbuild Syringe.sln /verbosity:minimal /p:WarningLevel=3 /p:Configuration=Release
  
branches:
  only:
    - master

services:
  - mongodb

before_build:
  ps: nuget restore Syringe.sln
