version: 1.0.{build}
shallow_clone: true
clone_depth: 1

cache:
  - packages ->  **\packages.config

build_script:
    - ps: .\build\build.ps1
  
branches:
  only:
    - master

services:
  - mongodb
  
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

after_build:
  - ps: .\build\nupkg-to-zip.ps1
  - 7z a Syringe-%APPVEYOR_BUILD_VERSION%.zip .\build\_deploymentOutput\*.zip
  - echo %APPVEYOR_BUILD_VERSION% > CURRENTVERSION.txt

environment:
    COVERALLS_REPO_TOKEN:  
       secure: umoRFggjKi3k6AUv84a9sxf/GYFsGm3weJh7zWLKfUTRnOJFlxN0KI5cntUhk2kV

after_test: 
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Syringe*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  src\Syringe.Tests\bin\release\Syringe.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  
artifacts:
  - path: Syringe-$(APPVEYOR_BUILD_VERSION).zip
    name: CurrentVersionZip
    
  - path: CURRENTVERSION.txt
    name: CurrentVersionTxt

# Url: https://yetanotherchris.blob.core.windows.net/syringe/currentversion.txt
# Azure Blob Explorer: http://clumsyleaf.com/products/downloads
deploy:
  provider: AzureBlob
  storage_account_name: yetanotherchris
  storage_access_key:
    secure: f99SukwJNZYbqSSR1ve8UFSq1Fc/0VRxUIiT/uK0diatTIP8MCsK8GWZu5ipzn8RwxXsR9ovVu6+kLGEKYyiBSlC7K9hlnidEhO4KO+G6STzsKXkDs1lzyk9hqEEDxFo
  container: syringe
  folder: 
  artifact: 
  unzip: false
