version: 1.0.{build}
shallow_clone: true
clone_depth: 1

environment:
    nodejs_version: "5.0"
    COVERALLS_REPO_TOKEN:  
       secure: umoRFggjKi3k6AUv84a9sxf/GYFsGm3weJh7zWLKfUTRnOJFlxN0KI5cntUhk2kV
    AZURE_ACCESS_KEY:
       secure: wmZaNtbPMfVDAKh+ZzDO67SYu4fXoGDsp4rzGGn5zYPZq7sr8IacOCVXrHpaZuePRMRuC+xwiUfQte2Q8SavMek7dTrIJZ1DysuMUufB76dXnBEtrN7U/Vyd/DQZWeih
    MYGET_ACCESS_KEY:
       secure: syrbd00vj9tSxTdWxrecqIKfGnKzNXhVb+R1oyGR3jBtLmDz5JtCRnaEaeJwkeI7

cache:
  - packages ->  **\packages.config

branches:
  only:
    - master

services:
  - mongodb

# Add NodeJS/Grunt for the SASS compilation
install:
  - gem install sass
  - cd .\src\Syringe.Web\
  - npm install 
  - npm install -g grunt-cli
  - npm test
  - cd ..\..\

# Update the assembly version numbers with the Appveyor version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Run grunt, and then the custom build script that runs Octopack
build_script:
    - grunt
    - ps: .\build\build.ps1

# Copy and convert all Octopack generated nupkg files into zip files
after_build:
  - ps: .\build\nupkg-to-zip.ps1
  - 7z a Syringe-%APPVEYOR_BUILD_VERSION%.zip .\build\_deploymentOutput\*.zip
  - echo %APPVEYOR_BUILD_VERSION% > currentversion.txt

# Generate test coverage and upload it to Coveralls.IO
after_test: 
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Syringe*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  src\Syringe.Tests\bin\release\Syringe.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  
artifacts:
  - path: Syringe-$(APPVEYOR_BUILD_VERSION).zip
    name: CurrentVersionZip
    
  - path: currentversion.txt
    name: CurrentVersionTxt

# Upload to Azure Blob Storage.
# Url: https://yetanotherchris.blob.core.windows.net/syringe/currentversion.txt
# Explorer: http://clumsyleaf.com/products/downloads
deploy:
  provider: AzureBlob
  storage_account_name: yetanotherchris
  storage_access_key: $(AZURE_ACCESS_KEY)
  container: syringe
  folder: 
  artifact: 
  unzip: false

# Clean old Azure Blob zip files, update their content types, and then push to Myget
after_deploy:
  - ps: tools\AzureStorageCleanup\AzureStorageCleanup.exe -storagename yetanotherchris -storagekey $env:AZURE_ACCESS_KEY -container syringe -mindaysold 7 -recursive
  - nuget push .\build\_deploymentOutput\Syringe.Service.%APPVEYOR_BUILD_VERSION%.0.nupkg %MYGET_ACCESS_KEY% -Source https://www.myget.org/F/syringe/api/v2/package
  - nuget push .\build\_deploymentOutput\Syringe.Web.%APPVEYOR_BUILD_VERSION%.0.nupkg %MYGET_ACCESS_KEY% -Source https://www.myget.org/F/syringe/api/v2/package