version: 1.0.{build}
shallow_clone: true
clone_depth: 1

cache:
  - packages ->  **\packages.config

build_script:
    - ps: $(APPVEYOR_PROJECT_SLUG)\build\build.ps1
  
branches:
  only:
    - master

services:
  - mongodb

after_build:
  - ps: $(APPVEYOR_PROJECT_SLUG)\build\nupkg-to-zip.ps1
  - ps: 7z a $(APPVEYOR_PROJECT_SLUG)\build\_deploymentOutput\$(APPVEYOR_BUILD_VERSION).zip $(APPVEYOR_PROJECT_SLUG)\build\_deploymentOutput\*.zip
  
artifacts:
  - path: $(APPVEYOR_PROJECT_SLUG)\build\_deploymentOutput\$(APPVEYOR_BUILD_VERSION).zip
    name: CurrentVersion

deploy:
  provider: AzureBlob
  storage_account_name: portalvhdshhv3xmk8gh157
  storage_access_key:
    secure: f99SukwJNZYbqSSR1ve8UFSq1Fc/0VRxUIiT/uK0diatTIP8MCsK8GWZu5ipzn8RwxXsR9ovVu6+kLGEKYyiBSlC7K9hlnidEhO4KO+G6STzsKXkDs1lzyk9hqEEDxFo
  container: syringe
  folder: 
  artifact: 
  unzip: false